name: Modu Derle
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Java Kurulumu
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
      - name: Klasorleri Temizle ve Derle
        run: |
          chmod +x gradlew
          ./gradlew clean build --no-daemon
      - name: Tum Projeyi Listele (Hata Ayiklama)
        run: find . -name "*.jar"
      - name: Bulunan Tum Jar Dosyalarini Topla
        uses: actions/upload-artifact@v4
        with:
          name: KelebekModu-Jar
          path: "**/*.jar"
